project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "Chapter 1 Challenge"
            file: content/01_journal/Chapter_1_Challenge.qmd
          - text: "Supervised ML Regression - 2"
            file: content/01_journal/Supervised_ML_Regression_2.qmd
          - text: "Automated ML with H20 (I)"
            file: content/01_journal/Automated_Machine_Learning_with_H2O.qmd
          - text: "Automated ML with H20 (II) & Performance Measures"
            file: content/01_journal/AUTO_ML_H20_2_Perf_Measure.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto